# Lab Two: Data Cleaning

Data cleaning is the very first part of any data analysis and/or machine learning project. In this lab, you will be going over some of the common data issues and applying suitable fixes.

##### Loading libraries needed and the data

In [145]:
import pandas as pd
import numpy as np

### Explaining the data we will be using for this and the next few labs

In this example, we have four datasets, two datasets from two different hypothetical clinics, "clinic1" and "clinic2" which diagnose patients with a novel device that takes many measurements. The final goal is to see if they have a particular disease or not.

Measurements taken from patients in the two clinics are presented in dataframes `df_1` and `df_c2`. We also have an inspection log, recorded in `df_3` and `df_4`, for the devices used in "clinic1" and "clinic2" where many variables from the device are measured.

Two of these variables, `'R1'` and `'R3'`, are believed to affect the readings taken from the patients. The `df_1` and `df_2` datasets are labelled with an actual diagnosis of whether the patient had the disease or not, and the goal is to predict the existence of the disease based on the measurements taken from the patients. Since the variables of the devices, measured in inspection, affects the measurements taken from patients in clinics, they should also be considered. Here are the data frames:

#### Note: Cells which have '[A]' represents the activity you have to do.

In [146]:
# loading the 'df_1_lab_2.csv' csv data
df = pd.read_csv('df_1_lab_2.csv')

# This makes it so we are able to see 100 rows when displaying the data
pd.set_option('display.max_rows', 100)

In [147]:
df.head()

Unnamed: 0 Examination Date                 Name  Gender  Age Mode  \
0           0       2011-06-10          Cody Watson    male   72    d   
1           1       2011-02-20        Jonathan Duke    male    9    e   
2           2       2011-06-27  Charlene Houseworth  female   59    f   
3           3       2010-09-22        Gregory Curci    Male   23    g   
4           4       2011-06-10          Cody Watson    male   72    d   

                    Q        M1        DD Diagnosis  
0                   _  5.058993  1.481877  negative  
1  104.08763319576146  6.531724  2.266884  negative  
2  102.90431521853222  6.273313  0.396333  positive  
3  152.65165533060298  7.333626  0.557534  positive  
4                   _  5.058993  1.481877  negative

## Looking at issues with the data

##### Unique values of the `'Gender'` feature.

In [148]:
df['Gender'].unique()

array(['male', 'female', 'Male', 'fmeale'], dtype=object)

In [149]:
df['Diagnosis'].unique()

array(['negative', 'positive', '_'], dtype=object)

##### Unique values of the `'Mode'` feature.

In [150]:
df['Mode'].unique()

array(['d', 'e', 'f', 'g', '_', 'F', 'h', 'a'], dtype=object)

##### Observing the data types of each column.

In [151]:
df.dtypes

Unnamed: 0            int64
Examination Date     object
Name                 object
Gender               object
Age                   int64
Mode                 object
Q                    object
M1                  float64
DD                  float64
Diagnosis            object
dtype: object

# Lab Activity One: Guided Data Cleaning

##### It is generally a good idea to make a copy of the master dataset for cleaning so you can always go back if ever needed.

In [152]:
df_clean = df.copy()

In [153]:
df_clean.head()

Unnamed: 0 Examination Date                 Name  Gender  Age Mode  \
0           0       2011-06-10          Cody Watson    male   72    d   
1           1       2011-02-20        Jonathan Duke    male    9    e   
2           2       2011-06-27  Charlene Houseworth  female   59    f   
3           3       2010-09-22        Gregory Curci    Male   23    g   
4           4       2011-06-10          Cody Watson    male   72    d   

                    Q        M1        DD Diagnosis  
0                   _  5.058993  1.481877  negative  
1  104.08763319576146  6.531724  2.266884  negative  
2  102.90431521853222  6.273313  0.396333  positive  
3  152.65165533060298  7.333626  0.557534  positive  
4                   _  5.058993  1.481877  negative

##### [A] Drop the `'Unnamed: 0'` column

In [154]:
df_clean = df_clean.drop(columns= ['Unnamed: 0'])

##### [A] Fix the data in the `'Gender'` column.
> Hint: make it so there are 2 unique entries, `'male'` and `'female'`.

In [155]:
df_clean['Gender'].replace({'Male' : 'male', 'fmeale' : 'female'})

0       male
1       male
2     female
3       male
4       male
5     female
6     female
7       male
8     female
9     female
10    female
11      male
12      male
13      male
14      male
15    female
16      male
17    female
18    female
19      male
20    female
21      male
22      male
23    female
24      male
25      male
26    female
27    female
28    female
29      male
30    female
31    female
32    female
33      male
34    female
35      male
36    female
37    female
38      male
39    female
40      male
41      male
42    female
43      male
44      male
45    female
46      male
47    female
48      male
49      male
50    female
51    female
52      male
53    female
54    female
55      male
56    female
57      male
58      male
59      male
60      male
Name: Gender, dtype: object

In [156]:
df_clean['Gender'].unique()

array(['male', 'female', 'Male', 'fmeale'], dtype=object)

##### [A] Fix the data in the `'Mode'` column.
> Hint: Check for lower and upper case entries

In [157]:
df_clean['Mode'].unique()

array(['d', 'e', 'f', 'g', '_', 'F', 'h', 'a'], dtype=object)

In [158]:
df_clean['Mode'].replace({'F' : 'f'})


0     d
1     e
2     f
3     g
4     d
5     g
6     _
7     f
8     f
9     f
10    _
11    e
12    f
13    f
14    f
15    e
16    e
17    d
18    _
19    f
20    e
21    f
22    g
23    f
24    e
25    f
26    e
27    e
28    _
29    g
30    e
31    f
32    f
33    f
34    e
35    f
36    f
37    h
38    e
39    d
40    f
41    g
42    g
43    e
44    f
45    e
46    f
47    f
48    d
49    f
50    e
51    f
52    a
53    f
54    _
55    e
56    e
57    e
58    f
59    e
60    f
Name: Mode, dtype: object

### Setting The Correct Data Type

##### [A] Change the `'Q'` column to numeric data `type(float64)` instead of `'object'`.

In [159]:
df_clean.head()

Examination Date                 Name  Gender  Age Mode                   Q  \
0       2011-06-10          Cody Watson    male   72    d                   _   
1       2011-02-20        Jonathan Duke    male    9    e  104.08763319576146   
2       2011-06-27  Charlene Houseworth  female   59    f  102.90431521853222   
3       2010-09-22        Gregory Curci    Male   23    g  152.65165533060298   
4       2011-06-10          Cody Watson    male   72    d                   _   

         M1        DD Diagnosis  
0  5.058993  1.481877  negative  
1  6.531724  2.266884  negative  
2  6.273313  0.396333  positive  
3  7.333626  0.557534  positive  
4  5.058993  1.481877  negative

In [160]:
df_clean['Q'] = pd.to_numeric(df_clean['Q'], errors = 'coerce')

##### [A] Convert `'Examination date'` column to `datetime` type.

In [161]:
df_clean['Examination Date'] = pd.to_datetime(df_clean['Examination Date'])

In [162]:
df_clean['Mode'].unique()

array(['d', 'e', 'f', 'g', '_', 'F', 'h', 'a'], dtype=object)

##### Using the `gender_type` key we set the `'Gender'` column as categorical data.

In [163]:
gender_type = pd.CategoricalDtype(categories=["female", "male"])

df_clean["Gender"] = df_clean["Gender"].astype(gender_type)

In [164]:
df_clean.dtypes

Examination Date    datetime64[ns]
Name                        object
Gender                    category
Age                          int64
Mode                        object
Q                          float64
M1                         float64
DD                         float64
Diagnosis                   object
dtype: object

##### [A] Replicate how we changed the gender column to categorical but this time for the `'Mode'` column.

In [165]:
mode_type = pd.CategoricalDtype(categories=['d', 'e', 'f', 'g', '_', 'h', 'a'])
df_clean["Mode"] = df_clean["Mode"].astype(mode_type)

##### [A] Again, change the `'Diagnosis'` column to categorical replicating above the example above.

In [166]:
diag_type = pd.CategoricalDtype(categories=['negative', 'positive', '_'])
df_clean["Diagnosis"] = df_clean["Diagnosis"].astype(diag_type)

### Duplicate Entries
- Duplicate entities in a dataset is not good to have as it  can use overfit and is redundant information

##### [A] Check for duplicate entries and delete them

In [167]:
duplicate_rows = df_clean.duplicated()
display(duplicate_rows)

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36     True
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
60    False
dtype: bool

In [168]:
df_clean = df_clean[~duplicate_rows]
df_clean.head()

Examination Date                 Name  Gender  Age Mode           Q  \
0       2011-06-10          Cody Watson    male   72    d         NaN   
1       2011-02-20        Jonathan Duke    male    9    e  104.087633   
2       2011-06-27  Charlene Houseworth  female   59    f  102.904315   
3       2010-09-22        Gregory Curci     NaN   23    g  152.651655   
5       2011-07-21        Linda Sawicki  female   17    g   67.239054   

         M1        DD Diagnosis  
0  5.058993  1.481877  negative  
1  6.531724  2.266884  negative  
2  6.273313  0.396333  positive  
3  7.333626  0.557534  positive  
5  3.642516  3.765706  positive

##### [A] Once you delete a row in your dataset the index of that row is also deleted. Reset the index of the dataset so it in proper order.
> Hint: use the `dataframe.reset_index` function and set the drop parameter to `True`.

In [169]:
#this code used to set the drop parameter to True.
df_clean = df_clean.reset_index(drop = True)

##### [A] Check the data types of your dataframe and print the shape of the dataframe.

In [170]:
df_clean.dtypes

Examination Date    datetime64[ns]
Name                        object
Gender                    category
Age                          int64
Mode                      category
Q                          float64
M1                         float64
DD                         float64
Diagnosis                 category
dtype: object

In [171]:
df_clean.shape

(59, 9)

# Lab Activity Two: Clean a Dataset Yourself

In this activity, you will need to clean the dataset yourself using the examples from the activity above. The `df_2_lab_2.csv` is loaded and displayed for you.

In [172]:
df_2 = pd.read_csv('df_2_lab_2.csv')
df_2.head(10)

Unnamed: 0 Inspection Date                   R1        R2        R3  \
0           0      2010-09-04  0.07960088091996784  0.007344  0.542921   
1           1      2010-09-27                    _  0.000204  9.613118   
2           2      2010-10-06                    _  0.000928  4.298943   
3           3      2010-10-21   0.8776172211437634  0.002254  9.240019   
4           4      2010-11-26                    _  0.008547  6.659528   
5           5      2010-11-29   0.7518246219719119  0.006172  7.023103   
6           6      2011-01-04   0.9279763002997659  0.000833  5.473454   
7           7      2011-01-28   0.9051137625634268  0.008793  7.223218   
8           8      2011-02-03  0.09188005264255929  0.001529  2.745545   
9           9      2011-02-04                    _  0.007507  4.472094   

         R4 Device Site  
0  0.000074     clinic1  
1  0.000042     clinic1  
2  0.000041     clinic1  
3  0.000182     clinic1  
4  0.000022     clinic1  
5  0.000016     clinic1  
6  0.000124     clinic2  
7  0.000209     clinic2  
8  0.000024     clinic1  
9  0.000035     clinic2

##### [A] Figure out the issues with this dataset and apply the cleaning methods

In [173]:
#Duplicate of the original data frame
df2_clean = df_2.copy()

In [174]:
#To check the shape of dataframe
df2_clean.shape

(22, 7)

In [175]:
#To show the first 10 rows
df2_clean.head(10)

Unnamed: 0 Inspection Date                   R1        R2        R3  \
0           0      2010-09-04  0.07960088091996784  0.007344  0.542921   
1           1      2010-09-27                    _  0.000204  9.613118   
2           2      2010-10-06                    _  0.000928  4.298943   
3           3      2010-10-21   0.8776172211437634  0.002254  9.240019   
4           4      2010-11-26                    _  0.008547  6.659528   
5           5      2010-11-29   0.7518246219719119  0.006172  7.023103   
6           6      2011-01-04   0.9279763002997659  0.000833  5.473454   
7           7      2011-01-28   0.9051137625634268  0.008793  7.223218   
8           8      2011-02-03  0.09188005264255929  0.001529  2.745545   
9           9      2011-02-04                    _  0.007507  4.472094   

         R4 Device Site  
0  0.000074     clinic1  
1  0.000042     clinic1  
2  0.000041     clinic1  
3  0.000182     clinic1  
4  0.000022     clinic1  
5  0.000016     clinic1  
6  0.000124     clinic2  
7  0.000209     clinic2  
8  0.000024     clinic1  
9  0.000035     clinic2

In [176]:
#this code is use to remove the column Unnamed: 0
df2_clean = df2_clean.drop( columns= ['Unnamed: 0'])

In [177]:
#Changing the 'R1' column to numeric data type(float64) instead of 'object'.
df2_clean['R1'] = pd.to_numeric(df2_clean['R1'], errors = 'coerce')

In [178]:
#Converting the Inspection Date column to datetime data type.
df2_clean['Inspection Date'] = pd.to_datetime(df2_clean['Inspection Date'])

In [179]:
#Checking the Unique values of Device Site Features
df2_clean['Device Site'].unique()

array(['clinic1', 'clinic2'], dtype=object)

In [180]:
#device_type key that we set the device type column as categorical data.
device_type = pd.CategoricalDtype(categories=['clinic1', 'clinic2'])
df2_clean["Device Site"] = df2_clean["Device Site"].astype(device_type)

In [181]:
#Check the data types of the dataframe and print the shape of the dataframe.
df2_clean.dtypes

Inspection Date    datetime64[ns]
R1                        float64
R2                        float64
R3                        float64
R4                        float64
Device Site              category
dtype: object

In [182]:
#Checking the Unique values of Inspection Date Features
df2_clean['Inspection Date'].unique()

array(['2010-09-04T00:00:00.000000000', '2010-09-27T00:00:00.000000000',
       '2010-10-06T00:00:00.000000000', '2010-10-21T00:00:00.000000000',
       '2010-11-26T00:00:00.000000000', '2010-11-29T00:00:00.000000000',
       '2011-01-04T00:00:00.000000000', '2011-01-28T00:00:00.000000000',
       '2011-02-03T00:00:00.000000000', '2011-02-04T00:00:00.000000000',
       '2011-02-17T00:00:00.000000000', '2011-02-27T00:00:00.000000000',
       '2011-03-10T00:00:00.000000000', '2011-04-10T00:00:00.000000000',
       '2011-05-21T00:00:00.000000000', '2011-05-30T00:00:00.000000000',
       '2011-05-31T00:00:00.000000000', '2011-06-10T00:00:00.000000000',
       '2011-07-17T00:00:00.000000000', '2011-07-24T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [183]:
#Checking the Unique values of R1 Features
df2_clean['R1'].unique()

array([0.07960088,        nan, 0.87761722, 0.75182462, 0.9279763 ,
       0.90511376, 0.09188005, 0.68392412, 0.60318716, 0.62296081,
       0.51084674, 0.8258057 , 0.4981389 , 0.4153777 , 0.63858706,
       0.36442741])

In [184]:
#Checking the Unique values of R2 Features
df2_clean['R2'].unique()

array([0.00734356, 0.0002041 , 0.00092786, 0.00225439, 0.00854714,
       0.00617227, 0.00083285, 0.00879283, 0.00152949, 0.00750652,
       0.00824557, 0.00595488, 0.00015293, 0.0022346 , 0.00996164,
       0.00887066, 0.00961029, 0.00039116, 0.00796753, 0.00124115,
       0.005587  , 0.00068982])

In [185]:
#Checking the Unique values of R3 Features
df2_clean['R3'].unique()

array([ 0.54292069,  9.61311816,  4.29894332,  9.24001932,  6.65952788,
        7.02310271,  5.47345392,  7.22321815,  2.74554509,  4.47209384,
        5.04736962,  5.68629602,  1.97180362, 11.65281021, 10.82207863,
       11.93315685,  5.15205577,  7.03626232,  4.19818239,  9.85027439,
       10.05301885,  2.70553273])

In [186]:
#Checking the Unique values of R34 Features
df2_clean['R4'].unique()

array([7.42982526e-05, 4.23192143e-05, 4.13526365e-05, 1.81675239e-04,
       2.21202704e-05, 1.59905553e-05, 1.23803608e-04, 2.08966155e-04,
       2.36015128e-05, 3.54215822e-05, 9.05373783e-05, 1.78653460e-04,
       1.65144352e-04, 1.20882505e-04, 8.43264859e-05, 1.53099230e-04,
       2.26573409e-04, 1.44945002e-04, 1.04024543e-05, 9.53562283e-05,
       2.79409824e-05, 7.02836096e-05])

In [187]:
#Check for duplicate entries and delete
duplicate_rows = df2_clean.duplicated()
display(duplicate_rows)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
dtype: bool

In [188]:
#Dropping the Duplicated rows
df2_clean = df2_clean[~duplicate_rows]

In [189]:
#this code used to set the drop parameter to True.
df2_clean = df2_clean.reset_index(drop = True)

In [190]:
#Checking the data types of the dataframe
df2_clean.dtypes

Inspection Date    datetime64[ns]
R1                        float64
R2                        float64
R3                        float64
R4                        float64
Device Site              category
dtype: object

In [191]:
#Use to print the shape of the dataframe.
df2_clean.shape

(22, 6)